######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 7 11:40:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gl_viewer.h viewer.h
FORMS += viewer.ui
SOURCES += gl_viewer.cc main.cc viewer.cc
QT += opengl
