######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 5 00:04:37 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += gl_viewer.h viewer.h
FORMS += viewer.ui viewer_2.ui
SOURCES += gl_viewer.cc main.cc viewer.cc
